#!/bin/bash
set -eu

wwwuser='nginx'
for f in "$@"; do
    if [[ -f "$f" ]]; then
        chmod 0640 "$f"
    elif [[ -d "$f" ]]; then
        chmod 0750 "$f"
    fi
    chown root:"$wwwuser" "$f"
done
