#!/bin/bash
set -u

if (( $# != 1 )); then
    return 1
fi
if [[ ! -d "$1" ]]; then
    echo 'Not a directory'
    return 1
fi
if [[ -f '.coverage' ]]; then
    coverage report --show-missing --include "${1}/*" --omit '*/tests/*,*/migrations/*'
fi
