#!/bin/bash

if ! hash jq; then
    echo "'jq' is missing"
    echo "please do something like 'zypper install jq'"
    exit 1
fi

if (( $# == 0 )); then
    if [[ "$(git rev-parse --is-inside-work-tree 2> /dev/null)" != "true" ]]; then
        echo "not in a git repo"
        exit 1
    fi
    repo=$(git remote get-url --all origin | cut -d':' -f2 | cut -d'.' -f-1)
else
    repo=$1
fi

curl --silent https://api.github.com/repos/"$repo"/releases/latest\
| jq '.assets[] | .browser_download_url'
