#!/bin/bash
set -eu
hash "$(which gs)" "$(which pdfunite)"

if [[ -z "$1" || ( ! -f "$1" ) || "$(file -ib "$1" | cut -f1 -d' ')" != 'application/pdf;' ]]
then
    echo 'No valid input file'
    exit 1
fi

x=(0 -421 0 -421)
y=(-297 -297 0 0)
tmpdir="$(mktemp -d)"

for i in {0..3}
do
    gs -q -dNOPAUSE -dBATCH -P- -dSAFER -sDEVICE=pdfwrite \
        -g4210x2975 -sOutputFile="$tmpdir/%05d$i.pdf" \
        -c "<</PageOffset [${x[$i]} ${y[$i]}]>> setpagedevice" \
        -f "$1"
done

pdfunite "$tmpdir"/*.pdf "${1/.pdf/-1x1.pdf}"
rm -r "$tmpdir"
