#!/bin/bash
set -u

(( $# == 1 )) || exit 1
if [[ "$1" == *@* ]]; then
    [[ "$1" =~ ^[a-z_][a-z0-9_]{0,30}@([a-z0-9][a-z0-9-]*[a-z0-9].?|[a-z0-9]+.?)+$ ]] || exit 1
    user="${1%%@*}"
    host="${1##*@}"
else
    [[ "$1" =~ ^([a-z0-9][a-z0-9-]*[a-z0-9].?|[a-z0-9]+.?)+$ ]] || exit 1
    user="$USER"
    host="$1"
fi

# shellcheck disable=SC2029
ssh "root@${host}" "mkdir ~${user}/.ssh; chown ${user}:users ~${user}/.ssh; tee -a ~${user}/.ssh/authorized_keys; chown ${user}:users ~${user}/.ssh/authorized_keys; chmod 0600 ~${user}/.ssh/authorized_keys" <~/.ssh/id_rsa.pub
